challenges/urls.py
from django.urls import path

from . import views

app_name = "challenges"
urlpatterns = [
    path('', views.index, name='index'),

    path('challenges/', views.list_challenges, name='list_challenges'),
    path('challenges/<int:challenge_id>/', views.show_challenge, name='show_challenge'),

    path('exploits/<int:exploit_id>/', views.show_exploit, name='show_exploit'),

    path('servers/', views.list_servers, name='list_servers'),
    path('servers/<int:server_id>', views.show_server, name='show_server')
]

flagnado/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("challenges.urls")),
    path('admin/', admin.site.urls),
]

challenges/models.py
from django.db import models

import subprocess

class Challenge(models.Model):
    enabled = models.BooleanField(default=True)
    name = models.CharField(max_length=30)
    port = models.IntegerField()

    def __str__(self):
        return self.name

def exploit_path(instance, filename):
    return "{}/exploit_{}.py".format(instance.challenge.name, instance.ranking)

class Exploit(models.Model):
    enabled = models.BooleanField(default=True)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    ranking = models.IntegerField()
    exploit_file = models.FileField(upload_to=exploit_path)
    
    def __str__(self):
        return "Exploit #{}".format(self.ranking)

    # Returns the stdout of a command (as a str)
    # https://github.com/zzzanderw/NFS-Status/blob/master/nfs_status.py#L85
    def get_stdout(cmd):
        try:
            result = subprocess.run(cmd.split(" "), stdout=subprocess.PIPE, timeout=20) # 5 sec timeout
            return result.stdout.decode("utf-8")
        except subprocess.TimeoutExpired:
            return "error"

    def run(self, ip):
        if not self.enabled:
            return "exploit disabled"
        try:
            command = "python2 {} flagnado {} {}".format(self.exploit_file.path, ip, self.challenge.port)
            output = Exploit.get_stdout(command)
            return output.split("FLAGSPLIT")[1].split("FLAGSPLIT")[0].strip()
        except:
            return "error"

class Server(models.Model):
    enabled = models.BooleanField(default=True)
    ip = models.GenericIPAddressField(verbose_name="IP Address", protocol="IPv4", default="0.0.0.0")
    challenges = models.ManyToManyField(Challenge)

    def __str__(self):
        return self.ip

runner/models.py
from django.db import models

import requests

from challenges.models import Challenge, Exploit, Server

# https://steelkiwi.com/blog/practical-application-singleton-design-pattern/
class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj

class Flag(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    submitted = models.BooleanField(default=False)
    challenge = models.ForeignKey(Challenge, on_delete=models.DO_NOTHING, blank=True, null=True)
    flag = models.CharField(max_length=50)

    def __str__(self):
        return "{} - {}... ({})".format(self.challenge, self.flag[:10], "submitted" if self.submitted else "not submitted")

    def submit(self):
        try:
            requests.post("http://plspwn.me:443", data={"flag": self.flag})

            self.submitted = True
            self.save()
        except:
            pass

class Run(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    successful = models.BooleanField(default=False)
    flag = models.ForeignKey(Flag, on_delete=models.DO_NOTHING, blank=True, null=True)
    challenge = models.ForeignKey(Challenge, on_delete=models.DO_NOTHING, blank=True, null=True)
    server = models.ForeignKey(Server, on_delete=models.DO_NOTHING, blank=True, null=True)
    exploit = models.ForeignKey(Exploit, on_delete=models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return "{} on {} using exploit {} ({})".format(self.challenge, self.server, self.exploit.ranking, "successful" if self.successful
         else "unsuccessful")

class RunnerConfig(SingletonModel):
    exploiter_enabled = models.BooleanField(default=True)
    exploiter_interval = models.IntegerField(default=300)

    flagger_enabled = models.BooleanField(default=True)
    flagger_interval = models.IntegerField(default=30)

    def __str__(self):
        return "Config"

challenges/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from .models import Challenge, Exploit, Server
from runner.models import Run, RunnerConfig

#####
# / #
#####

def index(request):
    num_servers = len(Server.objects.filter(enabled=True))
    num_challenges = len(Challenge.objects.filter(enabled=True))
    num_exploits = len(Exploit.objects.filter(enabled=True))

    config = RunnerConfig.load()
    
    runs = Run.objects.all().order_by("-timestamp")[:30]

    context = {
        "num_servers": num_servers,
        "num_challenges": num_challenges,
        "num_exploits": num_exploits,
        "cols": ["challenge", "server", "exploit", "result"],
        "runs": runs,
        "exploiter": config.exploiter_enabled,
        "flagger": config.flagger_enabled 
    }
    return render(request, "challenges/status.html", context)

###############
# /challenges #
###############

def list_challenges(request):
    challs = Challenge.objects.all().order_by("-enabled", "name")

    context = {
        "challenge_list": challs
    }
    return render(request, "challenges/index.html", context)

def show_challenge(request, challenge_id):
    challenge = get_object_or_404(Challenge, pk=challenge_id)

    runs = Run.objects.filter(challenge=challenge).order_by("-timestamp")[:30]

    context = {
        "challenge": challenge,
        "cols": ["server", "exploit", "result"],
        "runs": runs
    }
    return render(request, "challenges/show_challenge.html", context)

#############
# /exploits #
#############

def show_exploit(request, exploit_id):
    exploit = get_object_or_404(Exploit, pk=exploit_id)
    
    with open(exploit.exploit_file.path, "r") as f:
        script = f.read()

    context = {
        "exploit": exploit,
        "script": script
    }

    return render(request, "exploits/show_exploit.html", context)


############
# /servers #
############

def list_servers(request):
    servers = Server.objects.all().order_by("-enabled", "ip")
    return render(request, "servers/index.html", {"servers": servers})

def show_server(request, server_id):
    server = get_object_or_404(Server, pk=server_id)
    
    runs = Run.objects.filter(server=server).order_by("-timestamp")[:30]

    context = {
        "server": server,
        "cols": ["challenge", "exploit", "result"],
        "runs": runs
    }
    return render(request, "servers/show_server.html", context)

runner/views.py
from django.shortcuts import render

# Create your views here.

challenges/templates/challenges/index.html
{% extends 'includes/base.html' %}


{% block content %}
    <h2>Challenges</h2>
    <br>
    {% if challenge_list %}
        <ul>
        {% for challenge in challenge_list %}
            <li><a href="{% url 'challenges:show_challenge' challenge.id %}">{% include "includes/span_li.html" with data=challenge %}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No challenges configured</p>
    {% endif %}
{% endblock content %}

challenges/templates/challenges/show_challenge.html
{% extends 'includes/base.html' %}

{% block content %}
<h2>{{ challenge }} ({% if not challenge.enabled %}disabled; {% endif %}running on port {{ challenge.port }})</h2>
<br>
{% include "exploits/list_exploits.html" %}
<br>
{% include "includes/table.html" %}
{% endblock content %}

challenges/templates/challenges/status.html
{% extends 'includes/base.html' %}

{% block title %}
Flagnado | Status
{% endblock title %}

{% block content %}
<h1 style="text-align: center">Welcome to Flagnado</h1>
<br>
<br>
<h3>Game Status</h3>
<p>There are {{ num_servers }} active servers hosting {{ num_challenges }} active challenges, with {{ num_exploits }} total exploits.</p>
<p><h5>Exploiter Status: {% include "includes/span_state.html" with data=exploiter %}</h5></p>
<p><h5>Flagger Status: {% include "includes/span_state.html" with data=flagger %}</h5></p>
<br>
{% include "includes/table.html" %}
{% endblock content %}

challenges/templates/exploits/list_exploits.html
<h4>Exploits</h4>
{% if challenge.exploit_set.all %}
<ul>
    {% for exploit in challenge.exploit_set.all %}
        <li><a href="{% url 'challenges:show_exploit' exploit.id %}">{% include "includes/span_li.html" with data=exploit %}</a></li>
    {% endfor %}
</ul>
{% else %}
No exploits defined
{% endif %}

challenges/templates/exploits/show_exploit.html
{% extends 'includes/base.html' %}

{% block content %}
<h2>Script for {{ exploit.challenge.name }} exploit {{ exploit.ranking }}</h2>
<br>
<pre>
{% comment %} {{ script }} {% endcomment %}go to admin panel to download script
</pre>
{% endblock content %}

challenges/templates/includes/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'challenges/style.css' %}">

    <title>{% block title %}{{ page_title|default:"Flagnado" }}{% endblock title %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'challenges:index' %}">Flagnado</a>

          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'challenges:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'challenges:list_challenges' %}">Challenges</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'challenges:list_servers' %}">Servers</a>
            </li>
          </ul>
          
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" target="_blank" href="/admin/challenges/exploit/add/">Upload Exploit</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% static 'challenges/exploit_tmpl.py' %}">Exploit Template</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" target="_blank" href="/admin">Admin</a>
            </li>
          </ul>
      </div>
    </nav>

    <main role="main" class="container">
      {% block content %}
      Fill in the content
      {% endblock content %}
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

challenges/templates/includes/span_li.html
{% if data is not None %}
<span style="{{ data.enabled|yesno:',text-decoration: line-through;color: gray,'}}">{{ data }}</span>
{% else %}
you forgot the <pre>data</pre>
{% endif %}

challenges/templates/includes/span_state.html
{% if data is not None %}
    {% if data is True %}
    <span style="color: green">ENABLED</span>
    {% else %}
    <span style="color: red">DISABLED</span>
    {% endif %}
{% else %}
you forgot the <pre>data</pre>
{% endif %}

challenges/templates/includes/table.html
{% if runs %}
<h4>Log</h4>
<table class="table table-hover table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Timestamp (UTC)</th>
            {% for col in cols %}
            <th scope="col">{{ col|title }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for run in runs %}
        <tr>
            <td>{{ run.timestamp }}</td>
            {% if "challenge" in cols %}
            <td>{{ run.challenge }}</td>
            {% endif %}
            {% if "server" in cols %}
            <td>{{ run.server }}</td>
            {% endif %}
            {% if "exploit" in cols %}
            <td>{{ run.exploit }}</td>
            {% endif %}
            {% if "result" in cols %}
            <td class="{{ run.successful|yesno:'table-success,table-danger'}}">{{ run.successful|yesno:"Got flag,Failed" }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

challenges/templates/servers/index.html
{% extends 'includes/base.html' %}

{% block content %}
    <h2>Game Servers</h2>
    <br>
    {% if servers %}
        <ul>
        {% for server in servers %}
            <li><a href="{% url 'challenges:show_server' server.id %}">{% include "includes/span_li.html" with data=server %}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No servers configured</p>
    {% endif %}
{% endblock content %}

challenges/templates/servers/show_server.html
{% extends 'includes/base.html' %}

{% block content %}
<h2>Server at {{ server.ip }}{% if not server.enabled %} (disabled){% endif %}</h2>
<br>
Challenges running on this server:
<ul>
{% for challenge in server.challenges.all %}
    <li><a href="{% url 'challenges:show_challenge' challenge.id %}">{% include "includes/span_li.html" with data=challenge%}</a></li>
{% endfor %}
</ul>
<br>
{% include "includes/table.html" %}
{% endblock content %}